services:
  # frontend service (Next.js)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # backend service (FastAPI)
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload